# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GobstonesSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GobstonesSwift
    pod 'SDWebImage', '~>3.8'
    
  target 'GobstonesSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GobstonesSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
